### get-request-persons
GET http://localhost:3001/api/persons/

### delete-request-person
DELETE http://localhost:3001/api/persons/3

### post-request-persons
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "sdf",
    "number": 12321
}

### get-info
GET http://localhost:3001/info
